import 'package:flutter/material.dart';

class Character {
  late String name;
  late Image picture;
  late String race;
  late String gender;
  late String age;
  late String build;
  late String height;
  late String weight;
  late String skin;
  late String eyes;
  late String hair;
  late String birthplace;
  late String citizenship;
  late String ethnicity;
  late String accent;
  late String voice;
  late String tatoos;
  late String special;
  late String religion;
  late String style;
  late String personality;
  late String socialClass;
  late String occupation;
  late String reputation;
  late String hobby;
  late String habits;
  late String friends;
  late String family;
  late String relationship;
  late String alignment;
  late String definingMoment;
  late String secret;
  late String catchphrase;
  late String colorScheme;
  late String backstory;
  late String positiveTrait;
  late String flaw;
  late String strengths;
  late String weaknesses;
  late String likes;
  late String dislikes;
  late String quirks;
  late String phobias;
  late String identity;
  late String facade;
  late String trueSelf;
  late String goal;
  late String need;
  late String motivation;
  late String fate;

  Character({character,photo,info}) {
    name = character;
    picture = photo;
    race ;
    gender;
    age;
    build;
    height;
    weight;
    skin;
    eyes;
    hair;
    birthplace;
    citizenship;
    ethnicity;
    accent;
    voice;
    tatoos;
    special;
    religion;
    style;
    personality;
    socialClass;
    occupation;
    reputation;
    hobby;
    habits;
    friends;
    family;
    relationship;
    alignment;
    definingMoment;
    secret;
    catchphrase;
    colorScheme;
    backstory;
    positiveTrait;
    flaw;
    strengths;
    weaknesses;
    likes;
    dislikes;
    quirks;
    phobias;
    identity;
    facade;
    trueSelf;
    goal;
    need;
    motivation;
    fate;
  }
}