class ElementLists {

  final List<String> genres = [
    'Genre',
    'Detective',
    'Romance',
    'Comedy',
    'Horror',
    'Action',
    'Myth',
    'Coming of Age',
    'Sci-Fi',
    'Fantasy',
    'Crime',
    'Western',
    'Thriller',
  ];

  final List<String> themes = [
    'Theme',
    'Good vs. Evil',
    'The American Dream',
    'Redemption',
    'Power vs. Control',
    'The Danger of Unbridled Ambition',
    'Love vs. Duty',
    'Vanity of Wealth',
    'Stability vs. Adventure',
    'There\'s no place like home',
    'Discovering Inner Strength through Adversity',
    'Individuality vs. Conformity',
    'Morality vs. Patriotism',
    'Overcomming fear',
    'Forbidden Knowledge',
    'Invisible Insanity',
    'The Value of Hard Work',
    'The Power of Family',
    'Love Conquers All',
    'Man vs. His Creation',
    'Connection with an Other',
    'Overcoming Bias/Prejudice',
    'Navigating the Fog of Manipulation',
    'Conspiracy',
    'The Horrors of War',
    'The Power of Music',
    'Better to Have Friends than Wealth',
    'Dangers of Blind Patriotism',
    'Revenge',
    'Power Corrupts',
    'Jealousy',
    'Greatness from Small Beginnings',
    'Loyalty in Adversity',
    'Time Moves On Without Us',
    'Power Greater than Us',
    'The Power of Determination',
    'Brothers Before Women',
    'You Can\'t Really Go Home',
    'Class Differences',
    'The Cure is Worse than the Disease',
    'Generational Differences',
    'The End Justifies the Means',
    'The End Doesn\'t Justify the Means',
    'The Grass is Greener on the Other Side',
    'The Dangers of Greed',
    'The Duality of Man',
    'The Past Comes Back to Haunt Us',
    'Rebellion vs. Tyranny',
    'The Dangers of Playing God',
    'The Destruction of Beauty',
    'Conflict Between Work and Personal Life',
    'Overcomming Differences',
    'The Dangers of Love',
    'Idealism vs. Corruption',
    'Order vs. Chaos',
    'Acting for the Greater Good',
    'The Inevitability of Death',
    'Corruption of Justice',
    'People are Not so Dissimilar',
    'Difficulty Controlling Power',
    'Dangers of Giving in to Tempration',
    'Searching for Direction in Life',
    'Crime Doesn\'t Pay',
    'Paranoia',
    'Can\'t Escape the Past',
    'Mistaken Identity',
    'Fate vs. Free Will',
    'Fear of Failure',
    'Dangers of Immortality',
    'The Illusion of Control',
    'Disillusionment vs. Dreams',
    'Pride Goes Before the Fall',
    'Optimism – Power or Folly',
    'The Power of Names',
    'Man vs. Nature',
    'The Power of Nature',
    'Things Never Really Change',
    'Getting to Know Onesself',
    'Totalitarianism',
    'Technology - Pros & Cons',
    'Shedding Old Skin',
    'Religion - Virtues & Hipocracy',
    'Inner vs. Outer Self',
    'Temporality of Beauty',
    'Breaking Morals for Survival',
    'Wisdom through Experience',
    'Nostalgia',
    'Fear of Growing Up',
    'Tradition vs. Progress',
    'Coming of Age',
    'Loss of Innocence',
    'Loneliness',
    'Self-Reliance',
    'Difficulty of Being Vulnerable',
    'Circle of Life',
    'Loss of Humanity',
    'Science vs. Morality',
    'Humanity vs. Beasthood',
    'Mind vs. Strength',
    'Discovering Humanity',
    'Rivalry',
    'Self-destruction of Humanity',
  ];

}